name: Website Build

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - run: npm ci --legacy-peer-deps
      - run: npm run format:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - run: npm ci --legacy-peer-deps
      - run: npm run build
        env:
          CI: false



